name: Build and Push Docker Image
on: workflow_dispatch  # Changed from 'on: [push]' to manual trigger
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set Variables
        run: |
          echo "DATE_TAG=$(date +%Y-%m-%d)" >> $GITHUB_ENV
          echo "LATEST_TAG=latest" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "PROJECT_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV
          echo "IMAGE_NAME=${{ vars.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}" >> $GITHUB_ENV

      # Print env variables
      - name: Print Variables
        run: env
        
      - uses: docker/setup-buildx-action@v3
      
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }}-${{ env.DATE_TAG }}
            ${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }}-${{ env.LATEST_TAG }}
